export const general = {
    logo: "ecorebuild_images/logo.png",
    name: "EcoRebuild",
    address: "Amman, Jordan",
    intro: "punchline, paragraph",
    instagram: "https://www.instagram.com/eco_rebuild/",
    // facebook: "https://www.facebook.com/happy.mahdi/",
    // linkedin: "https://www.linkedin.com/in/ben-ayed-mehdi/",
    youtube: "https://www.youtube.com/channel/UCcJRMal-mHtTVnuU33jv9-Q",
    email: "info@ecorebuild.org",
    phone: "00962780106176",
    // website: "mehdibenayed.netlify.app",
    punchline: "Our mission is to create an eco-friendly community.",

    images: {
      img1: "ecorebuild_images/ecorebuildlogo.PNG",
      img2: "mehdi_images/speach.jpg",
      img3: "mehdi_images/mentor.jpg",
      img4: "mehdi_images/junctionxteam.jpg",
      img5: "mehdi_images/landing_img.jpg",
      img6: "mehdi_images/22.jfif",
      img7: "mehdi_images/speech.jpg",
      img8: "mehdi_images/graduationsuccess.jpg",
    },
  };
